# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20180202_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(upload_to='articles/, blank=True'),
        ),
    ]
